/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnvilCalculator: typeof import('./components/AnvilCalculator.vue')['default']
    AnvilResult: typeof import('./components/AnvilResult.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
